services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  backend:
    build:
      context: ./InventoryManagementAPI
      dockerfile: Dockerfile
    ports:
      - "5002:80"  # Changed from 5001 to 5002
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InventoryManagement;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    volumes:
      - aspnet-keys:/root/.aspnet/DataProtection-Keys

  frontend:
    build:
      context: ./inventory-management-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5002  # Update this to match the new backend port

volumes:
  sqlserver_data:
  aspnet-keys: